### ISSUE TITLE
[Feature request] add support for chrome url's?

### ISSUE THREAD

**Issue by Droyk** [samuthekid/tabrevolution#2]
So I do know that chrome doesn't give extension control over chrome urls but there is a flag and you know it, it's called "Extensions on chrome:// URLs" some devs did implement it 
https://stackoverflow.com/questions/19042857/can-you-access-chrome-pages-from-an-extension 
https://stackoverflow.com/questions/40159038/flag-extensions-on-chrome-urls-permission-name

I use great suspender extension and I have many pages that are suspended so if you add the support for chrome url's then my problem would be solved or if you can't then give user the power to solve the problem what you have to simply do is add a setting where user add which chrome url's they want to see tab revolution whenever they add a chrome url the extension will work on that what do you think?

**Comment by samuthekid** [comment]
Hi :)
I just updated the extension and it now supports chrome URLs, but unfortunately doesn't support other extensions URLs (even the URL is different ["chrome-extension://"]).
I did my research and I truly think that's impossible.
I'm sorry, I use the great suspender myself and I was looking for a solution too...
Thanks for understanding

**Comment by Droyk** [comment]
![image](https://cloud.githubusercontent.com/assets/15848350/24346272/2bdab246-12f1-11e7-9c97-52709e327c2f.png)
I can't update seeing this error

**Comment by samuthekid** [comment]
Sorry, I didn't see this... this should be fixed now.
