### ISSUE TITLE
I can t install it

### ISSUE THREAD

**Issue by badrelmers** [samuthekid/tabrevolution#3]
I always get this in chrome store 
Se ha producido un problema con la descarga. Ponte en contacto con el desarrollador o vuelve a intentarlo más tarde.

Invalid manifest

**Comment by samuthekid** [comment]
What is your operating system?

**Comment by badrelmers** [comment]
win 7 
Chrome 57.0.2987.98
I install from here https://chrome.google.com/webstore/detail/tab-revolution/mogjioenfopfpfgbeblmoapkcfpijkkn
Thanks

**Comment by svaisakh** [comment]
I get the message too on Ubuntu 16.04LTS, Chrome v58.0.3029.110 (64-bit)

**Comment by Helluuu** [comment]
Solved this issue by activating "chrome://flags/#extensions-on-chrome-urls" before installing the extension or by removing "chrome://*/*" in manifest.json:

And needed a manual reset after installing

	"content_scripts": [
		{
			"persistent": true,
			"js": ["jquery-3.0.0.js", "jquery-ui.js", "main.js", "style.css"],
			"matches": [**"chrome://*/*",** "<all_urls>"],
_and_

"permissions": [
		**"chrome://*/*",**

**Comment by Fake-Cake** [comment]
Same problem here
"There was a problem with the download. Please contact the developer or try again later.
Invalid manifest"
Google Chrome Version 58.0.3029.110 on Windows 7 32 bit

**Comment by samuthekid** [comment]
This problem is now solved :)
That feature (show tabs on chrome:// pages) is now disabled to prevent this type of errors.
Sorry for everything
